sandstorm-io/sandstorm-app-market

- app/client/templates/components/app-rating.html
- app/client/templates/components/app-rating.js
and thumbs down if >1 negative review
> Review bar now displays thumbs up if >1 + review 

- app/client/templates/single-app/single-app.js
No longer necessary/applicable.
> Revert ece9a26

- app/client/templates/components/menu.html
- app/client/templates/components/topbar.html
Also updated the "Upload App" link to go to our docs where App Submission instructions now live.
@kentonv
> Sandstorm logo goes home, upload app opens in new tab

- app/client/stylesheets/variables.scss
- app/client/templates/components/topbar.scss
Specifically:
- increased the size of the genre text
- removed all caps styling
- added bg colour to searchbar
- tweaked topbar item colours to better match the layout
@kentonv
> Improved legibility of genres and searchbar

- app/client/templates/components/components.scss
- app/client/templates/genres/genre.scss
- app/client/templates/login/login.scss
Also removed 2nd background colour.
> Legibility improvements to login buttons

- app/client/stylesheets/variables.scss
before this change
after this change
> Avoid clipped text on wide screens

- app/client/templates/components/app-item.html
- app/client/templates/components/app-item.js
- app/client/templates/components/app-item.scss
- app/client/templates/search/search.html
- app/client/templates/search/search.js
This is a bit scary since I couldn't think of a better way to highlight text than manually crafting the html string. I believe I'm escaping correctly (using `_.escape` from http://underscorejs.org/#escape), but it's worth triple-checking.
> Search shortDescription and highlight searchQuery

- app/client/stylesheets/variables.scss
- app/client/templates/components/topbar.scss
Perhaps the most responsive navigation bar I've ever seen.
> Fixed app grid padding and topbar responsiveness

- app/client/stylesheets/variables.scss
- app/client/templates/components/app-item.scss
- app/client/templates/components/app-rating.scss
- app/client/templates/single-app/single-app.scss
Just minor touch-ups to improve usability.
> Adding some hover colours

- app/client/templates/single-app/single-app.html
- app/client/templates/single-app/single-app.scss
> Hide prev/next on screenshot carousel & indicate meaning of "Last update" date

- meteor-bundle-main.js
Self-merging b/c I "own" the app market.
> Listen on fd=4, due to Sandstorm change

- app/client/templates/components/app-item-full-width.html
- app/client/templates/components/app-item-full-width.scss
- app/client/templates/single-app/single-app.html
- app/client/templates/single-app/single-app.scss
> Styled upstream author text to not look like a link

- README.md
- app/client/collections/genres.js
- app/client/templates/components/topbar.html
- app/client/templates/home/home.html
- settings-example.json
Also provide useful example settings.
> Call "Featured" what it is -- namely, "All"

- app/client/lib/appMarket.js
- app/client/templates/genres/genres.js
- app/client/templates/single-app/single-app.js
> Set page title on navigate

- app/client/templates/single-app/single-app.html
- app/client/templates/single-app/single-app.js
- app/client/templates/single-app/single-app.scss
Note:
- This is not the final design, but I'm pushing it now so @neynah
can style it further. Therefore it doesn't fully close the issue.
Refs #32
> Show two columns of reviews, and full text

- app/client/stylesheets/variables.scss
- app/client/templates/components/app-rating.html
- app/client/templates/components/app-rating.js
- app/client/templates/components/app-rating.scss
- app/client/templates/single-app/single-app.html
- app/client/templates/single-app/single-app.js
- app/client/templates/single-app/single-app.scss
Refs #59
Pushing now so @neynah can build other changes on top. Further changes
will be needed before deploying.
> Adjust review bar as needed

- app/client/stylesheets/variables.scss
- app/client/templates/single-app/single-app.html
- app/client/templates/single-app/single-app.scss
> More issue59

- app/client/templates/single-app/single-app.js
The "Edit your review" link would fail to show a button as purple. This
fixes that.
> Hotfix for bug introduced in #59

- app/client/templates/components/app-item.scss
> Show a color on hover of app card

- app/client/templates/components/app-rating.scss
- app/client/templates/single-app/single-app.html
> Stop limiting width of rating text

- app/client/templates/single-app/single-app.scss
Refs #81
This helps if you e.g. zoom your browser to 110% text.
> Remove unncessary width constraint

- app/client/templates/single-app/single-app.html
> Provide maxlength=500 to review textarea

- app/client/templates/components/app-item.js
> Highlight search results case-insensitively

- app/client/templates/single-app/single-app.js
> Sort reviews most-recent first

- app/client/startup/startup.js
- app/client/templates/search/search.js
> Ensure app descriptions are downloading during search

- app/client/templates/single-app/single-app.html
- app/client/templates/single-app/single-app.js
- app/client/templates/single-app/single-app.scss
Close #34
While we're at it, redesign the info box in the top-right to be more usable.
> Show a "Report issues" button

- app/client/templates/single-app/single-app.scss
Someone once told me that consistency was good.
> Make top and bottom margin same

- app/client/templates/single-app/single-app.html
@dwrensha noticed that we're inconsistent about if a "3" rating is "Awesome" or "Amazing". See e.g.
https://apps.sandstorm.io/app/m86q05rdvj14yvn78ghaxynqz7u2svw6rnttptxx49g1785cdv1h
This PR standardizes on Amazing.
@neynah if you prefer to standardize on "Awesome" please say so here. I'll do that if you prefer!
Otherwise I'll merge & deploy this about 3-4 hours from now.
> Awesome -- or amazing?

- app/client/templates/components/app-item.html
- app/client/templates/home/home.html
- app/client/templates/home/home.js
Thanks to @zarvox for mentioning these.
> Minor low bandwidth tweaks

- app/client/templates/home/home.html
Refs https://github.com/sandstorm-io/sandstorm/issues/2545
> Call it a productivity suite

- app/client/templates/components/app-item.scss.flex
- app/client/templates/single-app/single-app.scss
> Switch background-size from cover to contain on screenshots and app icons

- app/client/templates/genres/genres.html
- app/client/templates/genres/genres.js
- app/client/templates/home/home.html
- app/client/templates/home/home.js
- app/client/templates/home/home.scss
Close #119
Thanks to @jparyani  for helping me take care of lifecycles of DOM
elements
Thanks to @neynah for designing the footer.
> Add app market footer

- app/client/templates/home/home.html
> Remove app packaging services text
